# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/settings/views/ui/pomoc_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(467, 407)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setWordWrap(False)
        self.label_11.setOpenExternalLinks(True)
        self.label_11.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.version_lbl = QtWidgets.QLabel(self.groupBox)
        self.version_lbl.setOpenExternalLinks(False)
        self.version_lbl.setObjectName("version_lbl")
        self.gridLayout.addWidget(self.version_lbl, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.groupBox)
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout.addWidget(self.name_lbl, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setOpenExternalLinks(True)
        self.label_13.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setOpenExternalLinks(True)
        self.label_18.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setEnabled(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Informacje o wtyczce"))
        self.label_10.setText(_translate("Dialog", "Właściciel:"))
        self.label_7.setText(_translate("Dialog", "Zgłaszanie błędów:"))
        self.label_9.setText(_translate("Dialog", "<a href=\"https://envirosolutions.pl\">EnviroSolutions Sp. z o.o.</a>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://www.gov.pl/web/rozwoj\"><span style=\" text-decoration: underline; color:#0000ff;\">Ministerstwo Rozwoju,<br/>Pracy i Technologii</span></a></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><a href=\"https://www.gnu.org/licenses/gpl-3.0.html\">GNU General Public License v3.0</a></body></html>"))
        self.label_3.setText(_translate("Dialog", "Wersja wtyczki:"))
        self.version_lbl.setText(_translate("Dialog", "0.0"))
        self.label_20.setText(_translate("Dialog", "Nazwa wtyczki:"))
        self.label_6.setText(_translate("Dialog", "<a href=\"https://github.com/envirosolutionspl/wtyczka_qgis_app/issues\">issue tracker</a>"))
        self.label_8.setText(_translate("Dialog", "Twórca:"))
        self.label.setText(_translate("Dialog", "Repozytorium kodu:"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://github.com/envirosolutionspl/wtyczka_qgis_app\"><span style=\" text-decoration: underline; color:#0000ff;\">github/envirosolutionspl</span></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Licencja:"))
        self.name_lbl.setText(_translate("Dialog", "Wtyczka APP"))
        self.groupBox_2.setTitle(_translate("Dialog", "Podstawa prawna"))
        self.label_12.setText(_translate("Dialog", "Treść rozporządzenia:"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://dziennikustaw.gov.pl/D2020000191601.pdf\"><span style=\" text-decoration: underline; color:#0000ff;\">Rozporządzenie Ministra Rozwoju,<br/>Pracy i Technologii</span></a></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Dialog", "Materiały informacyjne"))
        self.label_17.setText(_translate("Dialog", "Filmy instruktażowe:"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://youtu.be/2BMjrvGA-x8\"><span style=\" text-decoration: underline; color:#0000ff;\">Filmy instruktażowe</span></a></p></body></html>"))
        self.label_19.setText(_translate("Dialog", "Instrukcja użytkownika:"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><a href=\"http://www.gov.pl/zagospodarowanieprzestrzenne/instrukcja-uzytkownika-wtyczka-app\"><span style=\" text-decoration: underline; color:#0000ff;\">Instrukcja użytkownika</span></a></p></body></html>"))
        self.cancel_btn.setText(_translate("Dialog", "Zamknij"))

