# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/metadata/views/ui/metadane_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(748, 642)
        font = QtGui.QFont()
        font.setKerning(True)
        Dialog.setFont(font)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.empty3_lbl = QtWidgets.QLabel(Dialog)
        self.empty3_lbl.setText("")
        self.empty3_lbl.setObjectName("empty3_lbl")
        self.verticalLayout.addWidget(self.empty3_lbl)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.chooseFile_widget = QgsFileWidget(Dialog)
        self.chooseFile_widget.setObjectName("chooseFile_widget")
        self.gridLayout_5.addWidget(self.chooseFile_widget, 0, 1, 1, 1)
        self.chooseSet_widget = QgsFileWidget(Dialog)
        self.chooseSet_widget.setObjectName("chooseSet_widget")
        self.gridLayout_5.addWidget(self.chooseSet_widget, 1, 1, 1, 1)
        self.addSet_lbl = QtWidgets.QLabel(Dialog)
        self.addSet_lbl.setObjectName("addSet_lbl")
        self.gridLayout_5.addWidget(self.addSet_lbl, 1, 0, 1, 1)
        self.existingMetadata_lbl = QtWidgets.QLabel(Dialog)
        self.existingMetadata_lbl.setObjectName("existingMetadata_lbl")
        self.gridLayout_5.addWidget(self.existingMetadata_lbl, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayoukt = QtWidgets.QHBoxLayout()
        self.horizontalLayoukt.setObjectName("horizontalLayoukt")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoukt.addItem(spacerItem)
        self.clearForm_btn = QtWidgets.QPushButton(Dialog)
        self.clearForm_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearForm_btn.setObjectName("clearForm_btn")
        self.horizontalLayoukt.addWidget(self.clearForm_btn)
        self.verticalLayout.addLayout(self.horizontalLayoukt)
        self.horizontal_line = QtWidgets.QFrame(Dialog)
        self.horizontal_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_line.setObjectName("horizontal_line")
        self.verticalLayout.addWidget(self.horizontal_line)
        self.titleForm_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleForm_lbl.setFont(font)
        self.titleForm_lbl.setObjectName("titleForm_lbl")
        self.verticalLayout.addWidget(self.titleForm_lbl)
        self.form_scrollArea = QtWidgets.QScrollArea(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_scrollArea.sizePolicy().hasHeightForWidth())
        self.form_scrollArea.setSizePolicy(sizePolicy)
        self.form_scrollArea.setWidgetResizable(True)
        self.form_scrollArea.setObjectName("form_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -1, 709, 300))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox.sizePolicy().hasHeightForWidth())
        self.mGroupBox.setSizePolicy(sizePolicy)
        self.mGroupBox.setCheckable(False)
        self.mGroupBox.setCollapsed(True)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.e1_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e1_lbl.setObjectName("e1_lbl")
        self.hboxlayout.addWidget(self.e1_lbl)
        self.e1_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e1_lineEdit.setPlaceholderText("")
        self.e1_lineEdit.setProperty("qgisRelation", "")
        self.e1_lineEdit.setObjectName("e1_lineEdit")
        self.hboxlayout.addWidget(self.e1_lineEdit)
        self.e1_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e1_tooltip.setText("")
        self.e1_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e1_tooltip.setObjectName("e1_tooltip")
        self.hboxlayout.addWidget(self.e1_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.e2_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e2_lbl.setObjectName("e2_lbl")
        self.hboxlayout1.addWidget(self.e2_lbl)
        self.e2_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e2_lineEdit.setProperty("qgisRelation", "")
        self.e2_lineEdit.setObjectName("e2_lineEdit")
        self.hboxlayout1.addWidget(self.e2_lineEdit)
        self.e2_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e2_tooltip.setText("")
        self.e2_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e2_tooltip.setObjectName("e2_tooltip")
        self.hboxlayout1.addWidget(self.e2_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.e3_lbl = QtWidgets.QLabel(self.mGroupBox)
        self.e3_lbl.setObjectName("e3_lbl")
        self.hboxlayout2.addWidget(self.e3_lbl)
        self.e3_lineEdit = QgsFilterLineEdit(self.mGroupBox)
        self.e3_lineEdit.setEnabled(False)
        self.e3_lineEdit.setProperty("qgisRelation", "")
        self.e3_lineEdit.setObjectName("e3_lineEdit")
        self.hboxlayout2.addWidget(self.e3_lineEdit)
        self.e3_tooltip = QtWidgets.QLabel(self.mGroupBox)
        self.e3_tooltip.setText("")
        self.e3_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e3_tooltip.setObjectName("e3_tooltip")
        self.hboxlayout2.addWidget(self.e3_tooltip)
        self.verticalLayout_2.addLayout(self.hboxlayout2)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.mGroupBox)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.e4_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.e4_lbl.setObjectName("e4_lbl")
        self.hboxlayout3.addWidget(self.e4_lbl)
        self.e4_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.e4_lineEdit.setProperty("qgisRelation", "")
        self.e4_lineEdit.setObjectName("e4_lineEdit")
        self.hboxlayout3.addWidget(self.e4_lineEdit)
        self.e4_tooltip = QtWidgets.QLabel(self.verticalGroupBox)
        self.e4_tooltip.setText("")
        self.e4_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e4_tooltip.setObjectName("e4_tooltip")
        self.hboxlayout3.addWidget(self.e4_tooltip)
        self.verticalLayout_3.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.e4_add_btn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.e4_add_btn.setObjectName("e4_add_btn")
        self.hboxlayout4.addWidget(self.e4_add_btn)
        self.e4_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox)
        self.e4_remove_btn.setObjectName("e4_remove_btn")
        self.hboxlayout4.addWidget(self.e4_remove_btn)
        self.verticalLayout_3.addLayout(self.hboxlayout4)
        self.e4_listWidget = QtWidgets.QListWidget(self.verticalGroupBox)
        self.e4_listWidget.setObjectName("e4_listWidget")
        self.verticalLayout_3.addWidget(self.e4_listWidget)
        self.verticalLayout_2.addWidget(self.verticalGroupBox)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.mGroupBox)
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.e5_lbl = QtWidgets.QLabel(self.verticalGroupBox1)
        self.e5_lbl.setObjectName("e5_lbl")
        self.hboxlayout5.addWidget(self.e5_lbl)
        self.e5_lineEdit = QgsFilterLineEdit(self.verticalGroupBox1)
        self.e5_lineEdit.setProperty("qgisRelation", "")
        self.e5_lineEdit.setObjectName("e5_lineEdit")
        self.hboxlayout5.addWidget(self.e5_lineEdit)
        self.e5_tooltip = QtWidgets.QLabel(self.verticalGroupBox1)
        self.e5_tooltip.setText("")
        self.e5_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e5_tooltip.setObjectName("e5_tooltip")
        self.hboxlayout5.addWidget(self.e5_tooltip)
        self.verticalLayout_31.addLayout(self.hboxlayout5)
        self.hboxlayout6 = QtWidgets.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.e5_add_btn = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.e5_add_btn.setObjectName("e5_add_btn")
        self.hboxlayout6.addWidget(self.e5_add_btn)
        self.e5_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.e5_remove_btn.setObjectName("e5_remove_btn")
        self.hboxlayout6.addWidget(self.e5_remove_btn)
        self.verticalLayout_31.addLayout(self.hboxlayout6)
        self.e5_listWidget = QtWidgets.QListWidget(self.verticalGroupBox1)
        self.e5_listWidget.setObjectName("e5_listWidget")
        self.verticalLayout_31.addWidget(self.e5_listWidget)
        self.verticalLayout_2.addWidget(self.verticalGroupBox1)
        self.verticalGroupBox2 = QtWidgets.QGroupBox(self.mGroupBox)
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.hboxlayout7 = QtWidgets.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.e6_lbl = QtWidgets.QLabel(self.verticalGroupBox2)
        self.e6_lbl.setObjectName("e6_lbl")
        self.hboxlayout7.addWidget(self.e6_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem1)
        self.e6_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox2)
        self.e6_cmbbx.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.e6_cmbbx.setObjectName("e6_cmbbx")
        self.e6_cmbbx.addItem("")
        self.e6_cmbbx.addItem("")
        self.hboxlayout7.addWidget(self.e6_cmbbx)
        self.e6_tooltip = QtWidgets.QLabel(self.verticalGroupBox2)
        self.e6_tooltip.setText("")
        self.e6_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e6_tooltip.setObjectName("e6_tooltip")
        self.hboxlayout7.addWidget(self.e6_tooltip)
        self.verticalLayout_32.addLayout(self.hboxlayout7)
        self.hboxlayout8 = QtWidgets.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.e6_add_btn = QtWidgets.QPushButton(self.verticalGroupBox2)
        self.e6_add_btn.setObjectName("e6_add_btn")
        self.hboxlayout8.addWidget(self.e6_add_btn)
        self.e6_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox2)
        self.e6_remove_btn.setObjectName("e6_remove_btn")
        self.hboxlayout8.addWidget(self.e6_remove_btn)
        self.verticalLayout_32.addLayout(self.hboxlayout8)
        self.e6_listWidget = QtWidgets.QListWidget(self.verticalGroupBox2)
        self.e6_listWidget.setObjectName("e6_listWidget")
        self.verticalLayout_32.addWidget(self.e6_listWidget)
        self.verticalLayout_2.addWidget(self.verticalGroupBox2)
        self.verticalGroupBox3 = QtWidgets.QGroupBox(self.mGroupBox)
        self.verticalGroupBox3.setObjectName("verticalGroupBox3")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.verticalGroupBox3)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.hboxlayout9 = QtWidgets.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.e7_lbl = QtWidgets.QLabel(self.verticalGroupBox3)
        self.e7_lbl.setObjectName("e7_lbl")
        self.hboxlayout9.addWidget(self.e7_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem2)
        self.e7_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e7_cmbbx.sizePolicy().hasHeightForWidth())
        self.e7_cmbbx.setSizePolicy(sizePolicy)
        self.e7_cmbbx.setObjectName("e7_cmbbx")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.setItemText(0, "")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.e7_cmbbx.addItem("")
        self.hboxlayout9.addWidget(self.e7_cmbbx)
        self.e7_tooltip = QtWidgets.QLabel(self.verticalGroupBox3)
        self.e7_tooltip.setText("")
        self.e7_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e7_tooltip.setObjectName("e7_tooltip")
        self.hboxlayout9.addWidget(self.e7_tooltip)
        self.verticalLayout_33.addLayout(self.hboxlayout9)
        self.hboxlayout10 = QtWidgets.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.e7_add_btn = QtWidgets.QPushButton(self.verticalGroupBox3)
        self.e7_add_btn.setObjectName("e7_add_btn")
        self.hboxlayout10.addWidget(self.e7_add_btn)
        self.e7_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox3)
        self.e7_remove_btn.setObjectName("e7_remove_btn")
        self.hboxlayout10.addWidget(self.e7_remove_btn)
        self.verticalLayout_33.addLayout(self.hboxlayout10)
        self.e7_listWidget = QtWidgets.QListWidget(self.verticalGroupBox3)
        self.e7_listWidget.setObjectName("e7_listWidget")
        self.verticalLayout_33.addWidget(self.e7_listWidget)
        self.verticalLayout_2.addWidget(self.verticalGroupBox3)
        self.gridLayout_2.addWidget(self.mGroupBox, 1, 0, 1, 2)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_2.sizePolicy().hasHeightForWidth())
        self.mGroupBox_2.setSizePolicy(sizePolicy)
        self.mGroupBox_2.setCollapsed(True)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.hboxlayout11 = QtWidgets.QHBoxLayout()
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.e8_lbl = QtWidgets.QLabel(self.mGroupBox_2)
        self.e8_lbl.setObjectName("e8_lbl")
        self.hboxlayout11.addWidget(self.e8_lbl)
        self.e8_lineEdit = QgsFilterLineEdit(self.mGroupBox_2)
        self.e8_lineEdit.setEnabled(False)
        self.e8_lineEdit.setProperty("qgisRelation", "")
        self.e8_lineEdit.setObjectName("e8_lineEdit")
        self.hboxlayout11.addWidget(self.e8_lineEdit)
        self.e8_tooltip = QtWidgets.QLabel(self.mGroupBox_2)
        self.e8_tooltip.setText("")
        self.e8_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e8_tooltip.setObjectName("e8_tooltip")
        self.hboxlayout11.addWidget(self.e8_tooltip)
        self.verticalLayout_21.addLayout(self.hboxlayout11)
        self.gridLayout_2.addWidget(self.mGroupBox_2, 2, 0, 1, 2)
        self.qgsCollapsibleGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qgsCollapsibleGroupBox.sizePolicy().hasHeightForWidth())
        self.qgsCollapsibleGroupBox.setSizePolicy(sizePolicy)
        self.qgsCollapsibleGroupBox.setCollapsed(True)
        self.qgsCollapsibleGroupBox.setObjectName("qgsCollapsibleGroupBox")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.qgsCollapsibleGroupBox)
        self.verticalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalGroupBox4 = QtWidgets.QGroupBox(self.qgsCollapsibleGroupBox)
        self.verticalGroupBox4.setObjectName("verticalGroupBox4")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.verticalGroupBox4)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.hboxlayout12 = QtWidgets.QHBoxLayout()
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.e9_lbl = QtWidgets.QLabel(self.verticalGroupBox4)
        self.e9_lbl.setObjectName("e9_lbl")
        self.hboxlayout12.addWidget(self.e9_lbl)
        self.e9_lineEdit = QgsFilterLineEdit(self.verticalGroupBox4)
        self.e9_lineEdit.setProperty("qgisRelation", "")
        self.e9_lineEdit.setObjectName("e9_lineEdit")
        self.hboxlayout12.addWidget(self.e9_lineEdit)
        self.e9_tooltip = QtWidgets.QLabel(self.verticalGroupBox4)
        self.e9_tooltip.setText("")
        self.e9_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e9_tooltip.setObjectName("e9_tooltip")
        self.hboxlayout12.addWidget(self.e9_tooltip)
        self.verticalLayout_34.addLayout(self.hboxlayout12)
        self.hboxlayout13 = QtWidgets.QHBoxLayout()
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.e10_lbl = QtWidgets.QLabel(self.verticalGroupBox4)
        self.e10_lbl.setObjectName("e10_lbl")
        self.hboxlayout13.addWidget(self.e10_lbl)
        self.e10_lineEdit = QgsFilterLineEdit(self.verticalGroupBox4)
        self.e10_lineEdit.setProperty("qgisRelation", "")
        self.e10_lineEdit.setObjectName("e10_lineEdit")
        self.hboxlayout13.addWidget(self.e10_lineEdit)
        self.e10_dateTimeEdit = QgsDateTimeEdit(self.verticalGroupBox4)
        self.e10_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e10_dateTimeEdit.setObjectName("e10_dateTimeEdit")
        self.hboxlayout13.addWidget(self.e10_dateTimeEdit)
        self.e10_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox4)
        self.e10_cmbbx.setObjectName("e10_cmbbx")
        self.e10_cmbbx.addItem("")
        self.e10_cmbbx.addItem("")
        self.e10_cmbbx.addItem("")
        self.hboxlayout13.addWidget(self.e10_cmbbx)
        self.e10_tooltip = QtWidgets.QLabel(self.verticalGroupBox4)
        self.e10_tooltip.setText("")
        self.e10_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e10_tooltip.setObjectName("e10_tooltip")
        self.hboxlayout13.addWidget(self.e10_tooltip)
        self.verticalLayout_34.addLayout(self.hboxlayout13)
        self.hboxlayout14 = QtWidgets.QHBoxLayout()
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.e9_add_btn = QtWidgets.QPushButton(self.verticalGroupBox4)
        self.e9_add_btn.setObjectName("e9_add_btn")
        self.hboxlayout14.addWidget(self.e9_add_btn)
        self.e9_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox4)
        self.e9_remove_btn.setObjectName("e9_remove_btn")
        self.hboxlayout14.addWidget(self.e9_remove_btn)
        self.verticalLayout_34.addLayout(self.hboxlayout14)
        self.e9_listWidget = QtWidgets.QListWidget(self.verticalGroupBox4)
        self.e9_listWidget.setObjectName("e9_listWidget")
        self.verticalLayout_34.addWidget(self.e9_listWidget)
        self.verticalLayout_22.addWidget(self.verticalGroupBox4)
        self.gridLayout_2.addWidget(self.qgsCollapsibleGroupBox, 3, 0, 1, 2)
        self.mGroupBox_4 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_4.sizePolicy().hasHeightForWidth())
        self.mGroupBox_4.setSizePolicy(sizePolicy)
        self.mGroupBox_4.setCollapsed(True)
        self.mGroupBox_4.setObjectName("mGroupBox_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.mGroupBox_4)
        self.verticalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalGroupBox5 = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.verticalGroupBox5.setObjectName("verticalGroupBox5")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.verticalGroupBox5)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.hboxlayout15 = QtWidgets.QHBoxLayout()
        self.hboxlayout15.setObjectName("hboxlayout15")
        self.e11_lbl = QtWidgets.QLabel(self.verticalGroupBox5)
        self.e11_lbl.setObjectName("e11_lbl")
        self.hboxlayout15.addWidget(self.e11_lbl)
        self.e11_lineEdit = QgsFilterLineEdit(self.verticalGroupBox5)
        self.e11_lineEdit.setProperty("qgisRelation", "")
        self.e11_lineEdit.setObjectName("e11_lineEdit")
        self.hboxlayout15.addWidget(self.e11_lineEdit)
        self.e11_tooltip = QtWidgets.QLabel(self.verticalGroupBox5)
        self.e11_tooltip.setText("")
        self.e11_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e11_tooltip.setObjectName("e11_tooltip")
        self.hboxlayout15.addWidget(self.e11_tooltip)
        self.verticalLayout_35.addLayout(self.hboxlayout15)
        self.hboxlayout16 = QtWidgets.QHBoxLayout()
        self.hboxlayout16.setObjectName("hboxlayout16")
        self.e11_add_btn = QtWidgets.QPushButton(self.verticalGroupBox5)
        self.e11_add_btn.setObjectName("e11_add_btn")
        self.hboxlayout16.addWidget(self.e11_add_btn)
        self.e11_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox5)
        self.e11_remove_btn.setObjectName("e11_remove_btn")
        self.hboxlayout16.addWidget(self.e11_remove_btn)
        self.verticalLayout_35.addLayout(self.hboxlayout16)
        self.e11_listWidget = QtWidgets.QListWidget(self.verticalGroupBox5)
        self.e11_listWidget.setObjectName("e11_listWidget")
        self.verticalLayout_35.addWidget(self.e11_listWidget)
        self.verticalLayout_23.addWidget(self.verticalGroupBox5)
        self.verticalGroupBox6 = QtWidgets.QGroupBox(self.mGroupBox_4)
        self.verticalGroupBox6.setObjectName("verticalGroupBox6")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.verticalGroupBox6)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.hboxlayout17 = QtWidgets.QHBoxLayout()
        self.hboxlayout17.setObjectName("hboxlayout17")
        self.e12_lbl = QtWidgets.QLabel(self.verticalGroupBox6)
        self.e12_lbl.setObjectName("e12_lbl")
        self.hboxlayout17.addWidget(self.e12_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout17.addItem(spacerItem3)
        self.e12_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox6)
        self.e12_cmbbx.setObjectName("e12_cmbbx")
        self.e12_cmbbx.addItem("")
        self.e12_cmbbx.addItem("")
        self.e12_cmbbx.addItem("")
        self.e12_cmbbx.addItem("")
        self.e12_cmbbx.addItem("")
        self.e12_cmbbx.addItem("")
        self.hboxlayout17.addWidget(self.e12_cmbbx)
        self.e12_tooltip = QtWidgets.QLabel(self.verticalGroupBox6)
        self.e12_tooltip.setText("")
        self.e12_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e12_tooltip.setObjectName("e12_tooltip")
        self.hboxlayout17.addWidget(self.e12_tooltip)
        self.verticalLayout_36.addLayout(self.hboxlayout17)
        self.hboxlayout18 = QtWidgets.QHBoxLayout()
        self.hboxlayout18.setObjectName("hboxlayout18")
        self.e12_add_btn = QtWidgets.QPushButton(self.verticalGroupBox6)
        self.e12_add_btn.setObjectName("e12_add_btn")
        self.hboxlayout18.addWidget(self.e12_add_btn)
        self.e12_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox6)
        self.e12_remove_btn.setObjectName("e12_remove_btn")
        self.hboxlayout18.addWidget(self.e12_remove_btn)
        self.verticalLayout_36.addLayout(self.hboxlayout18)
        self.e12_listWidget = QtWidgets.QListWidget(self.verticalGroupBox6)
        self.e12_listWidget.setObjectName("e12_listWidget")
        self.verticalLayout_36.addWidget(self.e12_listWidget)
        self.verticalLayout_23.addWidget(self.verticalGroupBox6)
        self.gridLayout_2.addWidget(self.mGroupBox_4, 4, 0, 1, 2)
        self.mGroupBox_5 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_5.setSizePolicy(sizePolicy)
        self.mGroupBox_5.setCollapsed(True)
        self.mGroupBox_5.setObjectName("mGroupBox_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.mGroupBox_5)
        self.verticalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.hboxlayout19 = QtWidgets.QHBoxLayout()
        self.hboxlayout19.setObjectName("hboxlayout19")
        self.e13_lbl = QtWidgets.QLabel(self.mGroupBox_5)
        self.e13_lbl.setObjectName("e13_lbl")
        self.hboxlayout19.addWidget(self.e13_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout19.addItem(spacerItem4)
        self.e13_dateTimeEdit = QgsDateTimeEdit(self.mGroupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e13_dateTimeEdit.sizePolicy().hasHeightForWidth())
        self.e13_dateTimeEdit.setSizePolicy(sizePolicy)
        self.e13_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e13_dateTimeEdit.setObjectName("e13_dateTimeEdit")
        self.hboxlayout19.addWidget(self.e13_dateTimeEdit)
        self.e13_cmbbx = QtWidgets.QComboBox(self.mGroupBox_5)
        self.e13_cmbbx.setEnabled(False)
        self.e13_cmbbx.setObjectName("e13_cmbbx")
        self.e13_cmbbx.addItem("")
        self.hboxlayout19.addWidget(self.e13_cmbbx)
        self.e13_tooltip = QtWidgets.QLabel(self.mGroupBox_5)
        self.e13_tooltip.setText("")
        self.e13_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e13_tooltip.setObjectName("e13_tooltip")
        self.hboxlayout19.addWidget(self.e13_tooltip)
        self.verticalLayout_24.addLayout(self.hboxlayout19)
        self.hboxlayout20 = QtWidgets.QHBoxLayout()
        self.hboxlayout20.setObjectName("hboxlayout20")
        self.e14_lbl = QtWidgets.QLabel(self.mGroupBox_5)
        self.e14_lbl.setObjectName("e14_lbl")
        self.hboxlayout20.addWidget(self.e14_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout20.addItem(spacerItem5)
        self.e14_dateTimeEdit = QgsDateTimeEdit(self.mGroupBox_5)
        self.e14_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e14_dateTimeEdit.setDate(QtCore.QDate(2020, 7, 28))
        self.e14_dateTimeEdit.setObjectName("e14_dateTimeEdit")
        self.hboxlayout20.addWidget(self.e14_dateTimeEdit)
        self.e14_cmbbx = QtWidgets.QComboBox(self.mGroupBox_5)
        self.e14_cmbbx.setEnabled(False)
        self.e14_cmbbx.setObjectName("e14_cmbbx")
        self.e14_cmbbx.addItem("")
        self.hboxlayout20.addWidget(self.e14_cmbbx)
        self.e14_tooltip = QtWidgets.QLabel(self.mGroupBox_5)
        self.e14_tooltip.setText("")
        self.e14_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e14_tooltip.setObjectName("e14_tooltip")
        self.hboxlayout20.addWidget(self.e14_tooltip)
        self.verticalLayout_24.addLayout(self.hboxlayout20)
        self.gridLayout_2.addWidget(self.mGroupBox_5, 5, 0, 1, 2)
        self.mGroupBox_6 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_6.sizePolicy().hasHeightForWidth())
        self.mGroupBox_6.setSizePolicy(sizePolicy)
        self.mGroupBox_6.setCollapsed(True)
        self.mGroupBox_6.setObjectName("mGroupBox_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.mGroupBox_6)
        self.verticalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.hboxlayout21 = QtWidgets.QHBoxLayout()
        self.hboxlayout21.setObjectName("hboxlayout21")
        self.e15_lbl = QtWidgets.QLabel(self.mGroupBox_6)
        self.e15_lbl.setObjectName("e15_lbl")
        self.hboxlayout21.addWidget(self.e15_lbl)
        self.e15_lineEdit = QgsFilterLineEdit(self.mGroupBox_6)
        self.e15_lineEdit.setProperty("qgisRelation", "")
        self.e15_lineEdit.setObjectName("e15_lineEdit")
        self.hboxlayout21.addWidget(self.e15_lineEdit)
        self.e15_tooltip = QtWidgets.QLabel(self.mGroupBox_6)
        self.e15_tooltip.setText("")
        self.e15_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e15_tooltip.setObjectName("e15_tooltip")
        self.hboxlayout21.addWidget(self.e15_tooltip)
        self.verticalLayout_25.addLayout(self.hboxlayout21)
        self.verticalGroupBox7 = QtWidgets.QGroupBox(self.mGroupBox_6)
        self.verticalGroupBox7.setObjectName("verticalGroupBox7")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.verticalGroupBox7)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.hboxlayout22 = QtWidgets.QHBoxLayout()
        self.hboxlayout22.setObjectName("hboxlayout22")
        self.e16_lbl = QtWidgets.QLabel(self.verticalGroupBox7)
        self.e16_lbl.setObjectName("e16_lbl")
        self.hboxlayout22.addWidget(self.e16_lbl)
        self.e16_lineEdit = QgsFilterLineEdit(self.verticalGroupBox7)
        self.e16_lineEdit.setProperty("qgisRelation", "")
        self.e16_lineEdit.setObjectName("e16_lineEdit")
        self.hboxlayout22.addWidget(self.e16_lineEdit)
        self.e16_tooltip = QtWidgets.QLabel(self.verticalGroupBox7)
        self.e16_tooltip.setText("")
        self.e16_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e16_tooltip.setObjectName("e16_tooltip")
        self.hboxlayout22.addWidget(self.e16_tooltip)
        self.verticalLayout_37.addLayout(self.hboxlayout22)
        self.hboxlayout23 = QtWidgets.QHBoxLayout()
        self.hboxlayout23.setObjectName("hboxlayout23")
        self.e16_add_btn = QtWidgets.QPushButton(self.verticalGroupBox7)
        self.e16_add_btn.setObjectName("e16_add_btn")
        self.hboxlayout23.addWidget(self.e16_add_btn)
        self.e16_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox7)
        self.e16_remove_btn.setObjectName("e16_remove_btn")
        self.hboxlayout23.addWidget(self.e16_remove_btn)
        self.verticalLayout_37.addLayout(self.hboxlayout23)
        self.e16_listWidget = QtWidgets.QListWidget(self.verticalGroupBox7)
        self.e16_listWidget.setObjectName("e16_listWidget")
        self.verticalLayout_37.addWidget(self.e16_listWidget)
        self.verticalLayout_25.addWidget(self.verticalGroupBox7)
        self.verticalGroupBox8 = QtWidgets.QGroupBox(self.mGroupBox_6)
        self.verticalGroupBox8.setObjectName("verticalGroupBox8")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.verticalGroupBox8)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.hboxlayout24 = QtWidgets.QHBoxLayout()
        self.hboxlayout24.setObjectName("hboxlayout24")
        self.e17_lbl = QtWidgets.QLabel(self.verticalGroupBox8)
        self.e17_lbl.setObjectName("e17_lbl")
        self.hboxlayout24.addWidget(self.e17_lbl)
        self.e17_lineEdit = QgsFilterLineEdit(self.verticalGroupBox8)
        self.e17_lineEdit.setEnabled(False)
        self.e17_lineEdit.setText("")
        self.e17_lineEdit.setProperty("qgisRelation", "")
        self.e17_lineEdit.setObjectName("e17_lineEdit")
        self.hboxlayout24.addWidget(self.e17_lineEdit)
        self.e17_tooltip = QtWidgets.QLabel(self.verticalGroupBox8)
        self.e17_tooltip.setText("")
        self.e17_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e17_tooltip.setObjectName("e17_tooltip")
        self.hboxlayout24.addWidget(self.e17_tooltip)
        self.verticalLayout_38.addLayout(self.hboxlayout24)
        self.hboxlayout25 = QtWidgets.QHBoxLayout()
        self.hboxlayout25.setObjectName("hboxlayout25")
        self.e17_add_btn = QtWidgets.QPushButton(self.verticalGroupBox8)
        self.e17_add_btn.setEnabled(False)
        self.e17_add_btn.setObjectName("e17_add_btn")
        self.hboxlayout25.addWidget(self.e17_add_btn)
        self.e17_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox8)
        self.e17_remove_btn.setEnabled(False)
        self.e17_remove_btn.setObjectName("e17_remove_btn")
        self.hboxlayout25.addWidget(self.e17_remove_btn)
        self.verticalLayout_38.addLayout(self.hboxlayout25)
        self.e17_listWidget = QtWidgets.QListWidget(self.verticalGroupBox8)
        self.e17_listWidget.setEnabled(False)
        self.e17_listWidget.setObjectName("e17_listWidget")
        self.verticalLayout_38.addWidget(self.e17_listWidget)
        self.verticalLayout_25.addWidget(self.verticalGroupBox8)
        self.gridLayout_2.addWidget(self.mGroupBox_6, 6, 0, 1, 2)
        self.mGroupBox_7 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_7.sizePolicy().hasHeightForWidth())
        self.mGroupBox_7.setSizePolicy(sizePolicy)
        self.mGroupBox_7.setCollapsed(True)
        self.mGroupBox_7.setObjectName("mGroupBox_7")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.mGroupBox_7)
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalGroupBox9 = QtWidgets.QGroupBox(self.mGroupBox_7)
        self.verticalGroupBox9.setObjectName("verticalGroupBox9")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.verticalGroupBox9)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.hboxlayout26 = QtWidgets.QHBoxLayout()
        self.hboxlayout26.setObjectName("hboxlayout26")
        self.e18_lbl = QtWidgets.QLabel(self.verticalGroupBox9)
        self.e18_lbl.setObjectName("e18_lbl")
        self.hboxlayout26.addWidget(self.e18_lbl)
        self.e18_lineEdit = QgsFilterLineEdit(self.verticalGroupBox9)
        self.e18_lineEdit.setProperty("qgisRelation", "")
        self.e18_lineEdit.setObjectName("e18_lineEdit")
        self.hboxlayout26.addWidget(self.e18_lineEdit)
        self.e18_dateTimeEdit = QgsDateTimeEdit(self.verticalGroupBox9)
        self.e18_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e18_dateTimeEdit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.e18_dateTimeEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.e18_dateTimeEdit.setObjectName("e18_dateTimeEdit")
        self.hboxlayout26.addWidget(self.e18_dateTimeEdit)
        self.e18_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox9)
        self.e18_cmbbx.setObjectName("e18_cmbbx")
        self.e18_cmbbx.addItem("")
        self.e18_cmbbx.addItem("")
        self.e18_cmbbx.addItem("")
        self.hboxlayout26.addWidget(self.e18_cmbbx)
        self.e18_tooltip = QtWidgets.QLabel(self.verticalGroupBox9)
        self.e18_tooltip.setText("")
        self.e18_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e18_tooltip.setObjectName("e18_tooltip")
        self.hboxlayout26.addWidget(self.e18_tooltip)
        self.verticalLayout_39.addLayout(self.hboxlayout26)
        self.hboxlayout27 = QtWidgets.QHBoxLayout()
        self.hboxlayout27.setObjectName("hboxlayout27")
        self.e19_lbl = QtWidgets.QLabel(self.verticalGroupBox9)
        self.e19_lbl.setObjectName("e19_lbl")
        self.hboxlayout27.addWidget(self.e19_lbl)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout27.addItem(spacerItem6)
        self.e19_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox9)
        self.e19_cmbbx.setObjectName("e19_cmbbx")
        self.e19_cmbbx.addItem("")
        self.e19_cmbbx.addItem("")
        self.e19_cmbbx.addItem("")
        self.hboxlayout27.addWidget(self.e19_cmbbx)
        self.e19_tooltip = QtWidgets.QLabel(self.verticalGroupBox9)
        self.e19_tooltip.setText("")
        self.e19_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e19_tooltip.setObjectName("e19_tooltip")
        self.hboxlayout27.addWidget(self.e19_tooltip)
        self.verticalLayout_39.addLayout(self.hboxlayout27)
        self.hboxlayout28 = QtWidgets.QHBoxLayout()
        self.hboxlayout28.setObjectName("hboxlayout28")
        self.e18_add_btn = QtWidgets.QPushButton(self.verticalGroupBox9)
        self.e18_add_btn.setObjectName("e18_add_btn")
        self.hboxlayout28.addWidget(self.e18_add_btn)
        self.e18_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox9)
        self.e18_remove_btn.setObjectName("e18_remove_btn")
        self.hboxlayout28.addWidget(self.e18_remove_btn)
        self.verticalLayout_39.addLayout(self.hboxlayout28)
        self.e18_listWidget = QtWidgets.QListWidget(self.verticalGroupBox9)
        self.e18_listWidget.setObjectName("e18_listWidget")
        self.verticalLayout_39.addWidget(self.e18_listWidget)
        self.verticalLayout_26.addWidget(self.verticalGroupBox9)
        self.gridLayout_2.addWidget(self.mGroupBox_7, 7, 0, 1, 2)
        self.mGroupBox_8 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_8.sizePolicy().hasHeightForWidth())
        self.mGroupBox_8.setSizePolicy(sizePolicy)
        self.mGroupBox_8.setCollapsed(True)
        self.mGroupBox_8.setObjectName("mGroupBox_8")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mGroupBox_8)
        self.verticalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalGroupBox10 = QtWidgets.QGroupBox(self.mGroupBox_8)
        self.verticalGroupBox10.setObjectName("verticalGroupBox10")
        self.verticalLayout_310 = QtWidgets.QVBoxLayout(self.verticalGroupBox10)
        self.verticalLayout_310.setObjectName("verticalLayout_310")
        self.hboxlayout29 = QtWidgets.QHBoxLayout()
        self.hboxlayout29.setObjectName("hboxlayout29")
        self.e20_lbl = QtWidgets.QLabel(self.verticalGroupBox10)
        self.e20_lbl.setObjectName("e20_lbl")
        self.hboxlayout29.addWidget(self.e20_lbl)
        self.e20_lineEdit = QgsFilterLineEdit(self.verticalGroupBox10)
        self.e20_lineEdit.setProperty("qgisRelation", "")
        self.e20_lineEdit.setObjectName("e20_lineEdit")
        self.hboxlayout29.addWidget(self.e20_lineEdit)
        self.e20_tooltip = QtWidgets.QLabel(self.verticalGroupBox10)
        self.e20_tooltip.setText("")
        self.e20_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e20_tooltip.setObjectName("e20_tooltip")
        self.hboxlayout29.addWidget(self.e20_tooltip)
        self.verticalLayout_310.addLayout(self.hboxlayout29)
        self.hboxlayout30 = QtWidgets.QHBoxLayout()
        self.hboxlayout30.setObjectName("hboxlayout30")
        self.e20_add_btn = QtWidgets.QPushButton(self.verticalGroupBox10)
        self.e20_add_btn.setObjectName("e20_add_btn")
        self.hboxlayout30.addWidget(self.e20_add_btn)
        self.e20_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox10)
        self.e20_remove_btn.setObjectName("e20_remove_btn")
        self.hboxlayout30.addWidget(self.e20_remove_btn)
        self.verticalLayout_310.addLayout(self.hboxlayout30)
        self.e20_listWidget = QtWidgets.QListWidget(self.verticalGroupBox10)
        self.e20_listWidget.setObjectName("e20_listWidget")
        self.verticalLayout_310.addWidget(self.e20_listWidget)
        self.verticalLayout_27.addWidget(self.verticalGroupBox10)
        self.hboxlayout31 = QtWidgets.QHBoxLayout()
        self.hboxlayout31.setObjectName("hboxlayout31")
        self.e21_lbl_2 = QtWidgets.QLabel(self.mGroupBox_8)
        self.e21_lbl_2.setObjectName("e21_lbl_2")
        self.hboxlayout31.addWidget(self.e21_lbl_2)
        self.e21_lineEdit = QgsFilterLineEdit(self.mGroupBox_8)
        self.e21_lineEdit.setEnabled(False)
        self.e21_lineEdit.setProperty("qgisRelation", "")
        self.e21_lineEdit.setObjectName("e21_lineEdit")
        self.hboxlayout31.addWidget(self.e21_lineEdit)
        self.e20_tooltip_2 = QtWidgets.QLabel(self.mGroupBox_8)
        self.e20_tooltip_2.setText("")
        self.e20_tooltip_2.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e20_tooltip_2.setObjectName("e20_tooltip_2")
        self.hboxlayout31.addWidget(self.e20_tooltip_2)
        self.verticalLayout_27.addLayout(self.hboxlayout31)
        self.gridLayout_2.addWidget(self.mGroupBox_8, 8, 0, 1, 2)
        self.mGroupBox_9 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.mGroupBox_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_9.sizePolicy().hasHeightForWidth())
        self.mGroupBox_9.setSizePolicy(sizePolicy)
        self.mGroupBox_9.setCollapsed(True)
        self.mGroupBox_9.setObjectName("mGroupBox_9")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.mGroupBox_9)
        self.verticalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalGroupBox11 = QtWidgets.QGroupBox(self.mGroupBox_9)
        self.verticalGroupBox11.setObjectName("verticalGroupBox11")
        self.verticalLayout_311 = QtWidgets.QVBoxLayout(self.verticalGroupBox11)
        self.verticalLayout_311.setObjectName("verticalLayout_311")
        self.hboxlayout32 = QtWidgets.QHBoxLayout()
        self.hboxlayout32.setObjectName("hboxlayout32")
        self.e22_lbl = QtWidgets.QLabel(self.verticalGroupBox11)
        self.e22_lbl.setObjectName("e22_lbl")
        self.hboxlayout32.addWidget(self.e22_lbl)
        self.e22_name_lineEdit = QgsFilterLineEdit(self.verticalGroupBox11)
        self.e22_name_lineEdit.setProperty("qgisRelation", "")
        self.e22_name_lineEdit.setObjectName("e22_name_lineEdit")
        self.hboxlayout32.addWidget(self.e22_name_lineEdit)
        self.e22_mail_lineEdit = QgsFilterLineEdit(self.verticalGroupBox11)
        self.e22_mail_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.e22_mail_lineEdit.setProperty("qgisRelation", "")
        self.e22_mail_lineEdit.setObjectName("e22_mail_lineEdit")
        self.hboxlayout32.addWidget(self.e22_mail_lineEdit)
        self.e22_tooltip = QtWidgets.QLabel(self.verticalGroupBox11)
        self.e22_tooltip.setText("")
        self.e22_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e22_tooltip.setObjectName("e22_tooltip")
        self.hboxlayout32.addWidget(self.e22_tooltip)
        self.verticalLayout_311.addLayout(self.hboxlayout32)
        self.hboxlayout33 = QtWidgets.QHBoxLayout()
        self.hboxlayout33.setObjectName("hboxlayout33")
        self.e23_lbl = QtWidgets.QLabel(self.verticalGroupBox11)
        self.e23_lbl.setObjectName("e23_lbl")
        self.hboxlayout33.addWidget(self.e23_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout33.addItem(spacerItem7)
        self.e23_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox11)
        self.e23_cmbbx.setObjectName("e23_cmbbx")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.e23_cmbbx.addItem("")
        self.hboxlayout33.addWidget(self.e23_cmbbx)
        self.e23_tooltip = QtWidgets.QLabel(self.verticalGroupBox11)
        self.e23_tooltip.setText("")
        self.e23_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e23_tooltip.setObjectName("e23_tooltip")
        self.hboxlayout33.addWidget(self.e23_tooltip)
        self.verticalLayout_311.addLayout(self.hboxlayout33)
        self.hboxlayout34 = QtWidgets.QHBoxLayout()
        self.hboxlayout34.setObjectName("hboxlayout34")
        self.e22_add_btn = QtWidgets.QPushButton(self.verticalGroupBox11)
        self.e22_add_btn.setObjectName("e22_add_btn")
        self.hboxlayout34.addWidget(self.e22_add_btn)
        self.e22_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox11)
        self.e22_remove_btn.setObjectName("e22_remove_btn")
        self.hboxlayout34.addWidget(self.e22_remove_btn)
        self.verticalLayout_311.addLayout(self.hboxlayout34)
        self.e22_listWidget = QtWidgets.QListWidget(self.verticalGroupBox11)
        self.e22_listWidget.setObjectName("e22_listWidget")
        self.verticalLayout_311.addWidget(self.e22_listWidget)
        self.verticalLayout_28.addWidget(self.verticalGroupBox11)
        self.gridLayout_2.addWidget(self.mGroupBox_9, 9, 0, 1, 2)
        self.mGroupBox_10 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_10.sizePolicy().hasHeightForWidth())
        self.mGroupBox_10.setSizePolicy(sizePolicy)
        self.mGroupBox_10.setCollapsed(True)
        self.mGroupBox_10.setObjectName("mGroupBox_10")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.mGroupBox_10)
        self.verticalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalGroupBox12 = QtWidgets.QGroupBox(self.mGroupBox_10)
        self.verticalGroupBox12.setObjectName("verticalGroupBox12")
        self.verticalLayout_312 = QtWidgets.QVBoxLayout(self.verticalGroupBox12)
        self.verticalLayout_312.setObjectName("verticalLayout_312")
        self.hboxlayout35 = QtWidgets.QHBoxLayout()
        self.hboxlayout35.setObjectName("hboxlayout35")
        self.e24_lbl = QtWidgets.QLabel(self.verticalGroupBox12)
        self.e24_lbl.setObjectName("e24_lbl")
        self.hboxlayout35.addWidget(self.e24_lbl)
        self.e24_lineEdit = QgsFilterLineEdit(self.verticalGroupBox12)
        self.e24_lineEdit.setProperty("qgisRelation", "")
        self.e24_lineEdit.setObjectName("e24_lineEdit")
        self.hboxlayout35.addWidget(self.e24_lineEdit)
        self.e24_tooltip = QtWidgets.QLabel(self.verticalGroupBox12)
        self.e24_tooltip.setText("")
        self.e24_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e24_tooltip.setObjectName("e24_tooltip")
        self.hboxlayout35.addWidget(self.e24_tooltip)
        self.verticalLayout_312.addLayout(self.hboxlayout35)
        self.hboxlayout36 = QtWidgets.QHBoxLayout()
        self.hboxlayout36.setObjectName("hboxlayout36")
        self.e25_lbl = QtWidgets.QLabel(self.verticalGroupBox12)
        self.e25_lbl.setObjectName("e25_lbl")
        self.hboxlayout36.addWidget(self.e25_lbl)
        self.e25_lineEdit = QgsFilterLineEdit(self.verticalGroupBox12)
        self.e25_lineEdit.setProperty("qgisRelation", "")
        self.e25_lineEdit.setObjectName("e25_lineEdit")
        self.hboxlayout36.addWidget(self.e25_lineEdit)
        self.e25_tooltip = QtWidgets.QLabel(self.verticalGroupBox12)
        self.e25_tooltip.setText("")
        self.e25_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e25_tooltip.setObjectName("e25_tooltip")
        self.hboxlayout36.addWidget(self.e25_tooltip)
        self.verticalLayout_312.addLayout(self.hboxlayout36)
        self.hboxlayout37 = QtWidgets.QHBoxLayout()
        self.hboxlayout37.setObjectName("hboxlayout37")
        self.e24_add_btn = QtWidgets.QPushButton(self.verticalGroupBox12)
        self.e24_add_btn.setObjectName("e24_add_btn")
        self.hboxlayout37.addWidget(self.e24_add_btn)
        self.e24_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox12)
        self.e24_remove_btn.setObjectName("e24_remove_btn")
        self.hboxlayout37.addWidget(self.e24_remove_btn)
        self.verticalLayout_312.addLayout(self.hboxlayout37)
        self.e24_listWidget = QtWidgets.QListWidget(self.verticalGroupBox12)
        self.e24_listWidget.setObjectName("e24_listWidget")
        self.verticalLayout_312.addWidget(self.e24_listWidget)
        self.verticalLayout_29.addWidget(self.verticalGroupBox12)
        self.gridLayout_2.addWidget(self.mGroupBox_10, 10, 0, 1, 2)
        self.mGroupBox_11 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_11.sizePolicy().hasHeightForWidth())
        self.mGroupBox_11.setSizePolicy(sizePolicy)
        self.mGroupBox_11.setCollapsed(True)
        self.mGroupBox_11.setObjectName("mGroupBox_11")
        self.verticalLayout_210 = QtWidgets.QVBoxLayout(self.mGroupBox_11)
        self.verticalLayout_210.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_210.setObjectName("verticalLayout_210")
        self.hboxlayout38 = QtWidgets.QHBoxLayout()
        self.hboxlayout38.setObjectName("hboxlayout38")
        self.e26_lbl = QtWidgets.QLabel(self.mGroupBox_11)
        self.e26_lbl.setObjectName("e26_lbl")
        self.hboxlayout38.addWidget(self.e26_lbl)
        self.e26_lineEdit = QgsFilterLineEdit(self.mGroupBox_11)
        self.e26_lineEdit.setEnabled(False)
        self.e26_lineEdit.setProperty("qgisRelation", "")
        self.e26_lineEdit.setObjectName("e26_lineEdit")
        self.hboxlayout38.addWidget(self.e26_lineEdit)
        self.e26_tooltip = QtWidgets.QLabel(self.mGroupBox_11)
        self.e26_tooltip.setText("")
        self.e26_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e26_tooltip.setObjectName("e26_tooltip")
        self.hboxlayout38.addWidget(self.e26_tooltip)
        self.verticalLayout_210.addLayout(self.hboxlayout38)
        self.verticalGroupBox13 = QtWidgets.QGroupBox(self.mGroupBox_11)
        self.verticalGroupBox13.setObjectName("verticalGroupBox13")
        self.verticalLayout_313 = QtWidgets.QVBoxLayout(self.verticalGroupBox13)
        self.verticalLayout_313.setObjectName("verticalLayout_313")
        self.hboxlayout39 = QtWidgets.QHBoxLayout()
        self.hboxlayout39.setObjectName("hboxlayout39")
        self.e27_lbl = QtWidgets.QLabel(self.verticalGroupBox13)
        self.e27_lbl.setObjectName("e27_lbl")
        self.hboxlayout39.addWidget(self.e27_lbl)
        self.e27_lineEdit = QgsFilterLineEdit(self.verticalGroupBox13)
        self.e27_lineEdit.setProperty("qgisRelation", "")
        self.e27_lineEdit.setObjectName("e27_lineEdit")
        self.hboxlayout39.addWidget(self.e27_lineEdit)
        self.e27_tooltip = QtWidgets.QLabel(self.verticalGroupBox13)
        self.e27_tooltip.setText("")
        self.e27_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e27_tooltip.setObjectName("e27_tooltip")
        self.hboxlayout39.addWidget(self.e27_tooltip)
        self.verticalLayout_313.addLayout(self.hboxlayout39)
        self.hboxlayout40 = QtWidgets.QHBoxLayout()
        self.hboxlayout40.setObjectName("hboxlayout40")
        self.e27_add_btn = QtWidgets.QPushButton(self.verticalGroupBox13)
        self.e27_add_btn.setObjectName("e27_add_btn")
        self.hboxlayout40.addWidget(self.e27_add_btn)
        self.e27_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox13)
        self.e27_remove_btn.setObjectName("e27_remove_btn")
        self.hboxlayout40.addWidget(self.e27_remove_btn)
        self.verticalLayout_313.addLayout(self.hboxlayout40)
        self.e27_listWidget = QtWidgets.QListWidget(self.verticalGroupBox13)
        self.e27_listWidget.setObjectName("e27_listWidget")
        self.verticalLayout_313.addWidget(self.e27_listWidget)
        self.verticalLayout_210.addWidget(self.verticalGroupBox13)
        self.hboxlayout41 = QtWidgets.QHBoxLayout()
        self.hboxlayout41.setObjectName("hboxlayout41")
        self.e28_lbl = QtWidgets.QLabel(self.mGroupBox_11)
        self.e28_lbl.setObjectName("e28_lbl")
        self.hboxlayout41.addWidget(self.e28_lbl)
        self.e28_lineEdit = QgsFilterLineEdit(self.mGroupBox_11)
        self.e28_lineEdit.setEnabled(False)
        self.e28_lineEdit.setProperty("qgisRelation", "")
        self.e28_lineEdit.setObjectName("e28_lineEdit")
        self.hboxlayout41.addWidget(self.e28_lineEdit)
        self.e28_tooltip = QtWidgets.QLabel(self.mGroupBox_11)
        self.e28_tooltip.setText("")
        self.e28_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e28_tooltip.setObjectName("e28_tooltip")
        self.hboxlayout41.addWidget(self.e28_tooltip)
        self.verticalLayout_210.addLayout(self.hboxlayout41)
        self.gridLayout_2.addWidget(self.mGroupBox_11, 11, 0, 1, 2)
        self.mGroupBox_12 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12.setSizePolicy(sizePolicy)
        self.mGroupBox_12.setCollapsed(True)
        self.mGroupBox_12.setObjectName("mGroupBox_12")
        self.verticalLayout_211 = QtWidgets.QVBoxLayout(self.mGroupBox_12)
        self.verticalLayout_211.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_211.setObjectName("verticalLayout_211")
        self.verticalGroupBox14 = QtWidgets.QGroupBox(self.mGroupBox_12)
        self.verticalGroupBox14.setObjectName("verticalGroupBox14")
        self.verticalLayout_314 = QtWidgets.QVBoxLayout(self.verticalGroupBox14)
        self.verticalLayout_314.setObjectName("verticalLayout_314")
        self.hboxlayout42 = QtWidgets.QHBoxLayout()
        self.hboxlayout42.setObjectName("hboxlayout42")
        self.e29_lbl = QtWidgets.QLabel(self.verticalGroupBox14)
        self.e29_lbl.setObjectName("e29_lbl")
        self.hboxlayout42.addWidget(self.e29_lbl)
        self.e29_name_lineEdit = QgsFilterLineEdit(self.verticalGroupBox14)
        self.e29_name_lineEdit.setProperty("qgisRelation", "")
        self.e29_name_lineEdit.setObjectName("e29_name_lineEdit")
        self.hboxlayout42.addWidget(self.e29_name_lineEdit)
        self.e29_cmbbx = QtWidgets.QComboBox(self.verticalGroupBox14)
        self.e29_cmbbx.setEnabled(False)
        self.e29_cmbbx.setEditable(False)
        self.e29_cmbbx.setObjectName("e29_cmbbx")
        self.e29_cmbbx.addItem("")
        self.hboxlayout42.addWidget(self.e29_cmbbx)
        self.e29_mail_lineEdit = QgsFilterLineEdit(self.verticalGroupBox14)
        self.e29_mail_lineEdit.setProperty("qgisRelation", "")
        self.e29_mail_lineEdit.setObjectName("e29_mail_lineEdit")
        self.hboxlayout42.addWidget(self.e29_mail_lineEdit)
        self.e29_tooltip = QtWidgets.QLabel(self.verticalGroupBox14)
        self.e29_tooltip.setText("")
        self.e29_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e29_tooltip.setObjectName("e29_tooltip")
        self.hboxlayout42.addWidget(self.e29_tooltip)
        self.verticalLayout_314.addLayout(self.hboxlayout42)
        self.hboxlayout43 = QtWidgets.QHBoxLayout()
        self.hboxlayout43.setObjectName("hboxlayout43")
        self.e29_add_btn = QtWidgets.QPushButton(self.verticalGroupBox14)
        self.e29_add_btn.setObjectName("e29_add_btn")
        self.hboxlayout43.addWidget(self.e29_add_btn)
        self.e29_remove_btn = QtWidgets.QPushButton(self.verticalGroupBox14)
        self.e29_remove_btn.setObjectName("e29_remove_btn")
        self.hboxlayout43.addWidget(self.e29_remove_btn)
        self.verticalLayout_314.addLayout(self.hboxlayout43)
        self.e29_listWidget = QtWidgets.QListWidget(self.verticalGroupBox14)
        self.e29_listWidget.setObjectName("e29_listWidget")
        self.verticalLayout_314.addWidget(self.e29_listWidget)
        self.verticalLayout_211.addWidget(self.verticalGroupBox14)
        self.hboxlayout44 = QtWidgets.QHBoxLayout()
        self.hboxlayout44.setObjectName("hboxlayout44")
        self.e30_lbl = QtWidgets.QLabel(self.mGroupBox_12)
        self.e30_lbl.setObjectName("e30_lbl")
        self.hboxlayout44.addWidget(self.e30_lbl)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout44.addItem(spacerItem8)
        self.e30_dateTimeEdit = QgsDateTimeEdit(self.mGroupBox_12)
        self.e30_dateTimeEdit.setEnabled(False)
        self.e30_dateTimeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.e30_dateTimeEdit.setObjectName("e30_dateTimeEdit")
        self.hboxlayout44.addWidget(self.e30_dateTimeEdit)
        self.e30_tooltip = QtWidgets.QLabel(self.mGroupBox_12)
        self.e30_tooltip.setText("")
        self.e30_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e30_tooltip.setObjectName("e30_tooltip")
        self.hboxlayout44.addWidget(self.e30_tooltip)
        self.verticalLayout_211.addLayout(self.hboxlayout44)
        self.hboxlayout45 = QtWidgets.QHBoxLayout()
        self.hboxlayout45.setObjectName("hboxlayout45")
        self.e31_lbl = QtWidgets.QLabel(self.mGroupBox_12)
        self.e31_lbl.setObjectName("e31_lbl")
        self.hboxlayout45.addWidget(self.e31_lbl)
        self.e31_lineEdit = QgsFilterLineEdit(self.mGroupBox_12)
        self.e31_lineEdit.setEnabled(False)
        self.e31_lineEdit.setProperty("qgisRelation", "")
        self.e31_lineEdit.setObjectName("e31_lineEdit")
        self.hboxlayout45.addWidget(self.e31_lineEdit)
        self.e31_tooltip = QtWidgets.QLabel(self.mGroupBox_12)
        self.e31_tooltip.setText("")
        self.e31_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e31_tooltip.setObjectName("e31_tooltip")
        self.hboxlayout45.addWidget(self.e31_tooltip)
        self.verticalLayout_211.addLayout(self.hboxlayout45)
        self.hboxlayout46 = QtWidgets.QHBoxLayout()
        self.hboxlayout46.setObjectName("hboxlayout46")
        self.e32_lbl = QtWidgets.QLabel(self.mGroupBox_12)
        self.e32_lbl.setObjectName("e32_lbl")
        self.hboxlayout46.addWidget(self.e32_lbl)
        self.e32_lineEdit = QgsFilterLineEdit(self.mGroupBox_12)
        self.e32_lineEdit.setEnabled(False)
        self.e32_lineEdit.setProperty("qgisRelation", "")
        self.e32_lineEdit.setObjectName("e32_lineEdit")
        self.hboxlayout46.addWidget(self.e32_lineEdit)
        self.e32_btn = QtWidgets.QPushButton(self.mGroupBox_12)
        self.e32_btn.setObjectName("e32_btn")
        self.hboxlayout46.addWidget(self.e32_btn)
        self.e32_tooltip = QtWidgets.QLabel(self.mGroupBox_12)
        self.e32_tooltip.setText("")
        self.e32_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e32_tooltip.setObjectName("e32_tooltip")
        self.hboxlayout46.addWidget(self.e32_tooltip)
        self.verticalLayout_211.addLayout(self.hboxlayout46)
        self.mGroupBox_12_5 = QgsCollapsibleGroupBox(self.mGroupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox_12_5.sizePolicy().hasHeightForWidth())
        self.mGroupBox_12_5.setSizePolicy(sizePolicy)
        self.mGroupBox_12_5.setObjectName("mGroupBox_12_5")
        self.verticalLayout_212 = QtWidgets.QVBoxLayout(self.mGroupBox_12_5)
        self.verticalLayout_212.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_212.setObjectName("verticalLayout_212")
        self.hboxlayout47 = QtWidgets.QHBoxLayout()
        self.hboxlayout47.setObjectName("hboxlayout47")
        self.e33_lbl = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.e33_lbl.setObjectName("e33_lbl")
        self.hboxlayout47.addWidget(self.e33_lbl)
        self.e33_lineEdit = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.e33_lineEdit.setEnabled(False)
        self.e33_lineEdit.setProperty("qgisRelation", "")
        self.e33_lineEdit.setObjectName("e33_lineEdit")
        self.hboxlayout47.addWidget(self.e33_lineEdit)
        self.e33_tooltip = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.e33_tooltip.setText("")
        self.e33_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e33_tooltip.setObjectName("e33_tooltip")
        self.hboxlayout47.addWidget(self.e33_tooltip)
        self.verticalLayout_212.addLayout(self.hboxlayout47)
        self.hboxlayout48 = QtWidgets.QHBoxLayout()
        self.hboxlayout48.setObjectName("hboxlayout48")
        self.e34_lbl = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.e34_lbl.setObjectName("e34_lbl")
        self.hboxlayout48.addWidget(self.e34_lbl)
        self.e34_lineEdit = QgsFilterLineEdit(self.mGroupBox_12_5)
        self.e34_lineEdit.setEnabled(False)
        self.e34_lineEdit.setProperty("qgisRelation", "")
        self.e34_lineEdit.setObjectName("e34_lineEdit")
        self.hboxlayout48.addWidget(self.e34_lineEdit)
        self.e34_tooltip = QtWidgets.QLabel(self.mGroupBox_12_5)
        self.e34_tooltip.setText("")
        self.e34_tooltip.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../img/info1.png"))
        self.e34_tooltip.setObjectName("e34_tooltip")
        self.hboxlayout48.addWidget(self.e34_tooltip)
        self.verticalLayout_212.addLayout(self.hboxlayout48)
        self.verticalLayout_211.addWidget(self.mGroupBox_12_5)
        self.gridLayout_2.addWidget(self.mGroupBox_12, 12, 0, 1, 2)
        self.form_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.form_scrollArea)
        self.empty1_lbl = QtWidgets.QLabel(Dialog)
        self.empty1_lbl.setText("")
        self.empty1_lbl.setObjectName("empty1_lbl")
        self.verticalLayout.addWidget(self.empty1_lbl)
        self.send_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send_lbl.setFont(font)
        self.send_lbl.setObjectName("send_lbl")
        self.verticalLayout.addWidget(self.send_lbl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.server_btn = QtWidgets.QPushButton(Dialog)
        self.server_btn.setEnabled(False)
        self.server_btn.setObjectName("server_btn")
        self.gridLayout.addWidget(self.server_btn, 0, 1, 1, 1)
        self.email_btn = QtWidgets.QPushButton(Dialog)
        self.email_btn.setEnabled(False)
        self.email_btn.setObjectName("email_btn")
        self.gridLayout.addWidget(self.email_btn, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.empty2_lbl = QtWidgets.QLabel(Dialog)
        self.empty2_lbl.setText("")
        self.empty2_lbl.setObjectName("empty2_lbl")
        self.verticalLayout.addWidget(self.empty2_lbl)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev_btn = QtWidgets.QPushButton(Dialog)
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_3.addWidget(self.prev_btn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.validateAndSave_btn = QtWidgets.QPushButton(Dialog)
        self.validateAndSave_btn.setObjectName("validateAndSave_btn")
        self.horizontalLayout_3.addWidget(self.validateAndSave_btn)
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setEnabled(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_lbl.setText(_translate("Dialog", "Metadane"))
        self.label.setText(_translate("Dialog", "Uwaga! Przed wczytaniem poniższych plików upewnij się, że są one poprawne. Możesz to zrobić np. za pomocą walidatora wtyczki APP. Wczytanie niezwalidowanego pliku może powodować niepoprawe wygenerowanie pliku XML metadanych."))
        self.addSet_lbl.setText(_translate("Dialog", "Wybierz plik GML dla zbioru APP (opcjonalne)"))
        self.existingMetadata_lbl.setText(_translate("Dialog", "Wczytaj istniejący plik z metadanymi (opcjonalne)    "))
        self.clearForm_btn.setText(_translate("Dialog", "Wyczyść formularz"))
        self.titleForm_lbl.setText(_translate("Dialog", "Formularz metadanych:"))
        self.mGroupBox.setTitle(_translate("Dialog", "Identyfikacja*"))
        self.e1_lbl.setText(_translate("Dialog", "Tytuł zbioru*"))
        self.e1_lineEdit.setText(_translate("Dialog", "Zbiór danych przestrzennych dla <typ_planu> <typ_jednostki> <nazwa_jednostki>"))
        self.e1_tooltip.setToolTip(_translate("Dialog", "Nazwa zbioru danych przestrzennych. \n"
"<br>\n"
"Nazwa zbioru danych przestrzennych musi być skonstruowana zgodnie ze wzorem dla:\n"
"<br>1)    planu zagospodarowania przestrzennego województwa: „Zbiór danych przestrzennych dla planu zagospodarowania przestrzennego województwa &lt;nazwa jednostki podziału administracyjnego kraju&gt;”;\n"
"<br>2)    studium uwarunkowań i kierunków zagospodarowania przestrzennego: „Zbiór danych przestrzennych dla studium uwarunkowań i kierunków zagospodarowania przestrzennego &lt;typ jednostki podziału administracyjnego kraju&gt; &lt;nazwa jednostki podziału administracyjnego kraju&gt;”,\n"
"<br>3)    miejscowych planów, w tym miejscowych planów zagospodarowania przestrzennego, miejscowych planów odbudowy oraz miejscowych planów rewitalizacji: „Zbiór danych przestrzennych dla miejscowych planów &lt;typ jednostki podziału administracyjnego kraju&gt; &lt;nazwa jednostki podziału administracyjnego kraju&gt;”.\n"
""))
        self.e2_lbl.setText(_translate("Dialog", "Streszczenie*"))
        self.e2_tooltip.setToolTip(_translate("Dialog", "Zwięzły opis zawartości zbioru danych przestrzennych."))
        self.e3_lbl.setText(_translate("Dialog", "Typ zbioru danych przestrzennych*"))
        self.e3_lineEdit.setText(_translate("Dialog", "dataset"))
        self.e3_tooltip.setToolTip(_translate("Dialog", "Typ zbioru danych przestrzennych opisywanego przez metadane. \n"
"\n"
"Wartości elementu metadanych zawsze jest równa: zbiór danych przestrzennych („dataset”).\n"
""))
        self.e4_lbl.setText(_translate("Dialog", "Adres zbioru danych przestrzennych*"))
        self.e4_tooltip.setToolTip(_translate("Dialog", "Adres zbioru danych przestrzennych określa odnośnik (odnośniki) do tego zbioru lub odnośnik do dodatkowych informacji na jego temat.\n"
"\n"
"Adres zbioru danych przestrzennych  musi być wyspecyfikowany w formie adresu URI:\n"
"1)    usługi sieciowej udostępniającej zbiór danych przestrzennych;\n"
"2)    strony internetowej zawierającej dodatkowe informacje na temat zbioru danych przestrzennych, lub jeżeli jest on niedostępny\n"
"3)    strony internetowej organizacji odpowiedzialnej za zbiór danych przestrzennych.\n"
""))
        self.e4_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e4_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e4_listWidget.setSortingEnabled(False)
        self.e5_lbl.setText(_translate("Dialog", "Unikalny identyfikator zbioru danych przestrzennych*"))
        self.e5_tooltip.setToolTip(_translate("Dialog", "Wartość, o której mowa w §4 rozporządzenia, identyfikująca dany zbiór danych przestrzennych w unikalny sposób."))
        self.e5_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e5_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e5_listWidget.setSortingEnabled(False)
        self.e6_lbl.setText(_translate("Dialog", "Język zbioru danych przestrzennych*"))
        self.e6_cmbbx.setItemText(0, _translate("Dialog", "polski"))
        self.e6_cmbbx.setItemText(1, _translate("Dialog", "angielski"))
        self.e6_tooltip.setToolTip(_translate("Dialog", "Język stosowany w zbiorze danych przestrzennych."))
        self.e6_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e6_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e6_listWidget.setSortingEnabled(False)
        self.e7_lbl.setText(_translate("Dialog", "Kodowanie znaków"))
        self.e7_cmbbx.setItemText(1, _translate("Dialog", "ucs2"))
        self.e7_cmbbx.setItemText(2, _translate("Dialog", "ucs4"))
        self.e7_cmbbx.setItemText(3, _translate("Dialog", "utf7"))
        self.e7_cmbbx.setItemText(4, _translate("Dialog", "utf8"))
        self.e7_cmbbx.setItemText(5, _translate("Dialog", "utf16"))
        self.e7_cmbbx.setItemText(6, _translate("Dialog", "8859część1"))
        self.e7_cmbbx.setItemText(7, _translate("Dialog", "8859część2"))
        self.e7_cmbbx.setItemText(8, _translate("Dialog", "8859część3"))
        self.e7_cmbbx.setItemText(9, _translate("Dialog", "8859część4"))
        self.e7_cmbbx.setItemText(10, _translate("Dialog", "8859część5"))
        self.e7_cmbbx.setItemText(11, _translate("Dialog", "8859część9"))
        self.e7_cmbbx.setItemText(12, _translate("Dialog", "8859część10"))
        self.e7_cmbbx.setItemText(13, _translate("Dialog", "8859część13"))
        self.e7_cmbbx.setItemText(14, _translate("Dialog", "8859część14"))
        self.e7_cmbbx.setItemText(15, _translate("Dialog", "8859część15"))
        self.e7_cmbbx.setItemText(16, _translate("Dialog", "8859część16"))
        self.e7_cmbbx.setItemText(17, _translate("Dialog", "usAscii"))
        self.e7_cmbbx.setItemText(18, _translate("Dialog", "ebcdic"))
        self.e7_tooltip.setToolTip(_translate("Dialog", "Nazwa sposobu kodowania znaków (informacji tekstowej) użytego w zbiorze danych przestrzennych."))
        self.e7_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e7_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e7_listWidget.setSortingEnabled(False)
        self.mGroupBox_2.setTitle(_translate("Dialog", "Klasyfikacja danych przestrzennych*"))
        self.e8_lbl.setText(_translate("Dialog", "Kategoria tematyczna*"))
        self.e8_lineEdit.setText(_translate("Dialog", "Planowanie/Kataster (planningCadastre)"))
        self.e8_tooltip.setToolTip(_translate("Dialog", "Klasyfikacja zbioru danych przestrzennych, opisana z użyciem wysokiego poziomu schematu klasyfikacyjnego wspomagającego grupowanie i ukierunkowane tematycznie wyszukiwanie dostępnych zbiorów danych przestrzennych.\n"
"\n"
"Wartość elementu metadanych zawsze jest równa: „Planowanie/Kataster” („planningCadastre”).\n"
""))
        self.qgsCollapsibleGroupBox.setTitle(_translate("Dialog", "Słowo kluczowe*"))
        self.e9_lbl.setText(_translate("Dialog", "Wartość słowa kluczowego*"))
        self.e9_tooltip.setToolTip(_translate("Dialog", "Słowo potocznie używane, słowo sformalizowane lub fraza stosowana do opisu danego tematu; podczas gdy kategorie tematyczne są zbyt ogólne dla zapytań szczegółowych, słowa kluczowe pomagają uszczegółowić wyszukiwanie pełnych tekstów oraz umożliwiają wyszukiwanie strukturalnych słów kluczowych.\n"
"\n"
"Obowiązkowo należy podać  słowa kluczowe:\n"
"•    opisujące odpowiedni temat danych przestrzennych i pozyskane z ogólnego wielojęzycznego tezaurusa środowiskowego (GEMET). Słowo to musi być równe: „Zagospodarowanie przestrzenne”,\n"
"•    opisujące poziom administracyjny, który zbiór danych przestrzennych obejmuje (zakres przestrzenny),\n"
"•    opisujące typ zbioru danych przestrzennych, w formie neutralnego językowo słowa równego: „PlannedLandUse”.\n"
"•    opisujące poziom jednostki administracyjnej objętej aktem planowania przestrzennego. Słowo to musi być równe zdefiniowanym w liście kodowej „Poziom planu zagospodarowania przestrzennego” zdefiniowanej w tabeli 2.7 w załączniku nr 1 do rozporządzenia.\n"
""))
        self.e10_lbl.setText(_translate("Dialog", "Standardowy słownik źródłowy"))
        self.e10_dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.e10_cmbbx.setItemText(0, _translate("Dialog", "Data utworzenia"))
        self.e10_cmbbx.setItemText(1, _translate("Dialog", "Data ostatniej aktualizacji"))
        self.e10_cmbbx.setItemText(2, _translate("Dialog", "Data opublikowania"))
        self.e10_tooltip.setToolTip(_translate("Dialog", "Nazwa sposobu kodowania znaków (informacji tekstowej) użytego w zbiorze danych."))
        self.e9_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e9_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e9_listWidget.setSortingEnabled(False)
        self.mGroupBox_4.setTitle(_translate("Dialog", "Położenie geograficzne*"))
        self.e11_lbl.setText(_translate("Dialog", "Geograficzny prostokąt ograniczający*"))
        self.e11_lineEdit.setToolTip(_translate("Dialog", "Prostokąt zdefiniowany jako <xmin>,<xmax>,<ymin>,<ymax> np.: 13.9000,23.9000,49.2300,54.7000"))
        self.e11_lineEdit.setPlaceholderText(_translate("Dialog", "np.: 13.9000,23.9000,49.2300,54.7000"))
        self.e11_tooltip.setToolTip(_translate("Dialog", "Zasięg zbioru danych przestrzennych w przestrzeni geograficznej, wyrażony za pomocą prostokąta ograniczającego, opisanego za pomocą południków granicy zachodniej i granicy wschodniej obszaru oraz równoleżników granicy południowej i granicy północnej wyrażonych w częściach dziesiętnych stopnia, z dokładnością do co najmniej czterech cyfr dziesiętnych.\n"
"\n"
"Jeżeli zbiór danych charakteryzuje się brakiem ciągłości przestrzennej, można określić więcej niż jeden prostokąt ograniczający.\n"
"\n"
"Współrzędne należy podać w Światowym Systemie Geodezyjnym 1984 (WGS84).\n"
""))
        self.e11_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e11_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e11_listWidget.setSortingEnabled(False)
        self.e12_lbl.setText(_translate("Dialog", "System odniesienia za pomocą współrzędnych*"))
        self.e12_cmbbx.setItemText(0, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/2180"))
        self.e12_cmbbx.setItemText(1, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/2176"))
        self.e12_cmbbx.setItemText(2, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/2177"))
        self.e12_cmbbx.setItemText(3, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/2178"))
        self.e12_cmbbx.setItemText(4, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/2179"))
        self.e12_cmbbx.setItemText(5, _translate("Dialog", "http://www.opengis.net/def/crs/EPSG/0/4258"))
        self.e12_tooltip.setToolTip(_translate("Dialog", "System odniesienia za pomocą współrzędnych zastosowany dla zbioru danych przestrzennych.\n"
"\n"
"Należy podać identyfikator systemu odniesienia w EPSG Geodetic Parameter Registry.\n"
""))
        self.e12_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e12_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e12_listWidget.setSortingEnabled(False)
        self.mGroupBox_5.setTitle(_translate("Dialog", "Odniesienie czasowe*"))
        self.e13_lbl.setText(_translate("Dialog", "Data utworzenia*"))
        self.e13_cmbbx.setItemText(0, _translate("Dialog", "Data utworzenia"))
        self.e13_tooltip.setToolTip(_translate("Dialog", "Data utworzenia zbioru danych przestrzennych.\n"
"\n"
"Wartość elementu musi  wyrażać co najmniej datę dzienną, która  może być rozszerzona o wskazanie czasu (godzina, minuta, sekunda).\n"
""))
        self.e14_lbl.setText(_translate("Dialog", "Data opublikowania"))
        self.e14_cmbbx.setItemText(0, _translate("Dialog", "Data opublikowania"))
        self.e14_tooltip.setToolTip(_translate("Dialog", "Data udostępnienia zbioru danych przestrzennych za pośrednictwem usług sieciowych.\n"
"Wartość elementu musi  wyrażać co najmniej datę dzienną, która  może być rozszerzona o wskazanie czasu (godzina, minuta, sekunda).\n"
""))
        self.mGroupBox_6.setTitle(_translate("Dialog", "Jakość i ważność*"))
        self.e15_lbl.setText(_translate("Dialog", "Pochodzenie*"))
        self.e15_tooltip.setToolTip(_translate("Dialog", "Opis historii procesu tworzenia lub ogólnej jakości zbioru danych przestrzennych. W stosownych przypadkach może zawierać stwierdzenie, czy zbiór danych przestrzennych był przedmiotem procesu kontroli lub oceny jakości, czy stanowi wersję urzędową i czy posiada moc prawną."))
        self.e16_lbl.setText(_translate("Dialog", "Rozdzielczość przestrzenna*"))
        self.e16_tooltip.setToolTip(_translate("Dialog", "Wielkość opisująca poziom szczegółowości zbioru danych przestrzennych, podawana jako skala równorzędna, wyrażona za pomocą liczby całkowitej stanowiącej mianownik skali."))
        self.e16_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e16_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e16_listWidget.setSortingEnabled(False)
        self.e17_lbl.setText(_translate("Dialog", "Typ reprezentacji przestrzennej*"))
        self.e17_tooltip.setToolTip(_translate("Dialog", "Metoda przestrzennej reprezentacji danych zbioru danych przestrzennych.\n"
"\n"
"Element metadanych zawsze przyjmuje wartości: wektor („Vector”) oraz siatka („Grid”).\n"
""))
        self.e17_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e17_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e17_listWidget.setSortingEnabled(False)
        self.mGroupBox_7.setTitle(_translate("Dialog", "Zgodność*"))
        self.e18_lbl.setText(_translate("Dialog", "Specyfikacja*"))
        self.e18_dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.e18_cmbbx.setItemText(0, _translate("Dialog", "Data utworzenia"))
        self.e18_cmbbx.setItemText(1, _translate("Dialog", "Data opublikowania"))
        self.e18_cmbbx.setItemText(2, _translate("Dialog", "Data ostatniej aktualizacji"))
        self.e18_tooltip.setToolTip(_translate("Dialog", "Przytoczenie przepisów lub innej specyfikacji, której odpowiada zbiór danych przestrzennych. \n"
"<br>\n"
"Przytoczenie powinno obejmować co najmniej:\n"
"<br>•    tytuł,\n"
"<br>•    datę odniesienia.\n"
"<br>\n"
"<br>Należy przytoczyć co najmniej: \n"
"<br>1.    Rozporządzenie Komisji (UE) Nr 1089/2010 z dnia 23 listopada 2010 r. w sprawie wykonania dyrektywy 2007/2/WE Parlamentu Europejskiego i Rady w zakresie interoperacyjności zbiorów i usług danych przestrzennych z późn. zm.\n"
"<br>2.    Specyfikację danych dla tematu „zagospodarowanie przestrzenne” - D2.8.III.4 Data Specification on Land Use – Technical Guidelines\n"
"<br>3.    Rozporządzenie Ministra Rozwoju w sprawie zbiorów danych przestrzennych oraz metadanych w zakresie zagospodarowania przestrzennego.\n"
"<br>4.    Specyfikację danych „Planowanie przestrzenne”\n"
""))
        self.e19_lbl.setText(_translate("Dialog", "Stopień*"))
        self.e19_cmbbx.setItemText(0, _translate("Dialog", "Zgodny (conformant)"))
        self.e19_cmbbx.setItemText(1, _translate("Dialog", "Niezgodny (notConformant)"))
        self.e19_cmbbx.setItemText(2, _translate("Dialog", "Brak oceny zgodności (notEvaluated)"))
        self.e19_tooltip.setToolTip(_translate("Dialog", "Stopień zgodności zbioru danych przestrzennych z przepisami przytoczonymi w ramach elementu E18 (specyfikacja)."))
        self.e18_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e18_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e18_listWidget.setSortingEnabled(False)
        self.mGroupBox_8.setTitle(_translate("Dialog", "Wymogi dotyczące dostępu i użytkowania*"))
        self.e20_lbl.setText(_translate("Dialog", "Warunki dotyczące dostępu i użytkowania*"))
        self.e20_tooltip.setToolTip(_translate("Dialog", "Warunki dostępu do zbiorów danych przestrzennych, a w stosownych przypadkach - również informacje o odpowiednich opłatach.\n"
"\n"
"Wartość elementu metadanych zawsze jest równa: Brak warunków dostępu i użytkowania.\n"
""))
        self.e20_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e20_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e20_listWidget.setSortingEnabled(False)
        self.e21_lbl_2.setText(_translate("Dialog", "Ograniczenia w publicznym dostępie*"))
        self.e21_lineEdit.setText(_translate("Dialog", "Brak ograniczeń w publicznym dostępie"))
        self.e20_tooltip_2.setToolTip(_translate("Dialog", "Informacje dotyczące ograniczeń publicznego dostępu do zbioru danych przestrzennych.\n"
"\n"
"Wartość elementu metadanych zawsze jest równa: Brak ograniczeń w publicznym dostępie.\n"
""))
        self.mGroupBox_9.setTitle(_translate("Dialog", "Organizacje odpowiedzialne*"))
        self.e22_lbl.setText(_translate("Dialog", "Jednostka odpowiedzialna*"))
        self.e22_name_lineEdit.setToolTip(_translate("Dialog", "nazwa jednostki"))
        self.e22_name_lineEdit.setPlaceholderText(_translate("Dialog", "nazwa jednostki"))
        self.e22_mail_lineEdit.setToolTip(_translate("Dialog", "adres email"))
        self.e22_mail_lineEdit.setPlaceholderText(_translate("Dialog", "adres email"))
        self.e22_tooltip.setToolTip(_translate("Dialog", "Opis organizacji odpowiedzialnej za tworzenie, przechowywanie, rozpowszechnianie zbioru danych przestrzennych oraz zarządzanie nim, pozwalający na identyfikację, nawiązanie kontaktu i komunikację z organizacją lub osobami związanymi ze zbiorem danych przestrzennych.\n"
"\n"
"Opis powinien obejmować co najmniej:\n"
"•    nazwę organizacji,\n"
"•    dane kontaktowe (adres poczty elektronicznej).\n"
"\n"
"Co najmniej należy wyspecyfikować jednostkę odpowiedzialną, pełniącą w stosunku do zbioru danych przestrzennych rolę „Administrator”, o której mowa w punkcie 13.5.\n"
""))
        self.e23_lbl.setText(_translate("Dialog", "Rola jednostki odpowiedzialnej*"))
        self.e23_cmbbx.setItemText(0, _translate("Dialog", "Administrator (custodian)"))
        self.e23_cmbbx.setItemText(1, _translate("Dialog", "Dostawca zasobu (resourceProvider)"))
        self.e23_cmbbx.setItemText(2, _translate("Dialog", "Właściciel (owner)"))
        self.e23_cmbbx.setItemText(3, _translate("Dialog", "Użytkownik (user)"))
        self.e23_cmbbx.setItemText(4, _translate("Dialog", "Dystrybutor (distributor)"))
        self.e23_cmbbx.setItemText(5, _translate("Dialog", "Twórca (originator)"))
        self.e23_cmbbx.setItemText(6, _translate("Dialog", "Punkt kontaktowy (pointOfContact)"))
        self.e23_cmbbx.setItemText(7, _translate("Dialog", "Główny badacz (principalInvestigator)"))
        self.e23_cmbbx.setItemText(8, _translate("Dialog", "Jednostka przetwarzająca (processor)"))
        self.e23_cmbbx.setItemText(9, _translate("Dialog", "Wydawca (publisher)"))
        self.e23_cmbbx.setItemText(10, _translate("Dialog", "Autor (author)"))
        self.e23_tooltip.setToolTip(_translate("Dialog", "Rola pełniona przez jednostkę odpowiedzialną w stosunku do zbioru danych przestrzennych."))
        self.e22_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e22_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e22_listWidget.setSortingEnabled(False)
        self.mGroupBox_10.setTitle(_translate("Dialog", "Kodowanie*"))
        self.e24_lbl.setText(_translate("Dialog", "Nazwa formatu*"))
        self.e24_tooltip.setToolTip(_translate("Dialog", "Nazwa formatu danych, w jakim dokonuje się dystrybucji zbioru danych przestrzennych."))
        self.e25_lbl.setText(_translate("Dialog", "Wersja formatu*"))
        self.e25_tooltip.setToolTip(_translate("Dialog", "Wersja formatu danych, w jakim dokonuje się dystrybucji zbioru danych przestrzennych."))
        self.e24_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e24_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e24_listWidget.setSortingEnabled(False)
        self.mGroupBox_11.setTitle(_translate("Dialog", "Informacje o utrzymaniu zbioru*"))
        self.e26_lbl.setText(_translate("Dialog", "Częstotliwość aktualizacji*"))
        self.e26_lineEdit.setText(_translate("Dialog", "według potrzeb"))
        self.e26_tooltip.setToolTip(_translate("Dialog", "Częstotliwość, z jaką dokonywane są zmiany w zbiorze danych przestrzennych, po tym jak zbiór danych przestrzennych został skompletowany.\n"
"\n"
"Wartości elementu metadanych zawsze jest równa: według potrzeb („asNeeded”).\n"
""))
        self.e27_lbl.setText(_translate("Dialog", "Informacja o szczegółowych wymaganiach dotyczących utrzymania*"))
        self.e27_tooltip.setToolTip(_translate("Dialog", "Szczegółowe informacje dotyczące sposobu przeprowadzania aktualizacji zbioru danych przestrzennych. "))
        self.e27_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e27_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e27_listWidget.setSortingEnabled(False)
        self.e28_lbl.setText(_translate("Dialog", "Zakres danych*"))
        self.e28_lineEdit.setText(_translate("Dialog", "Zbiór danych przestrzennych (dataset)"))
        self.e28_tooltip.setToolTip(_translate("Dialog", "Zakres danych, wobec których stosowana jest aktualizacja.\n"
"\n"
"Wartości elementu metadanych zawsze jest równa: zbiór danych przestrzennych („dataset”).\n"
""))
        self.mGroupBox_12.setTitle(_translate("Dialog", "Metadane na temat metadanych*"))
        self.e29_lbl.setText(_translate("Dialog", "Punkt kontaktowy metadanych*"))
        self.e29_name_lineEdit.setToolTip(_translate("Dialog", "nazwa organizacji"))
        self.e29_name_lineEdit.setPlaceholderText(_translate("Dialog", "nazwa organizacji"))
        self.e29_cmbbx.setItemText(0, _translate("Dialog", "Punkt kontaktowy (pointOfContact)"))
        self.e29_mail_lineEdit.setToolTip(_translate("Dialog", "adres email"))
        self.e29_mail_lineEdit.setPlaceholderText(_translate("Dialog", "adres email"))
        self.e29_tooltip.setToolTip(_translate("Dialog", "Opis organizacji odpowiedzialnej za tworzenie i przechowywanie metadanych.\n"
"Opis powinien obejmować co najmniej:\n"
"•    nazwę organizacji,\n"
"•    rolę organizacji,\n"
"•    dane kontaktowe (adres poczty elektronicznej).\n"
"\n"
"Wartość elementu metadanych rola jednostki zawsze jest równa: punkt kontaktowy („contactPoint”).\n"
""))
        self.e29_add_btn.setText(_translate("Dialog", "Dodaj"))
        self.e29_remove_btn.setText(_translate("Dialog", "Usuń"))
        self.e29_listWidget.setSortingEnabled(False)
        self.e30_lbl.setText(_translate("Dialog", "Data metadanych*"))
        self.e30_dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.e30_tooltip.setToolTip(_translate("Dialog", "Data określająca, kiedy utworzono lub zaktualizowano rekord metadanych.\n"
"\n"
"Wartość elementu należy podać z dokładnością dzienną (data dzienna).\n"
""))
        self.e31_lbl.setText(_translate("Dialog", "Język metadanych*"))
        self.e31_lineEdit.setText(_translate("Dialog", "polski"))
        self.e31_tooltip.setToolTip(_translate("Dialog", "Język, w którym wyrażone są elementy metadanych.\n"
"\n"
"Wartość elementu metadanych zawsze jest równa: polski.\n"
""))
        self.e32_lbl.setText(_translate("Dialog", "Unikalny identyfikator rekordu (pliku) metadanych*"))
        self.e32_btn.setToolTip(_translate("Dialog", "W przypadku nadpisywania (edycji) istniejącego pliku metadanych należy zostawić automatycznie zaczytany identyfikator"))
        self.e32_btn.setText(_translate("Dialog", "Generuj nowy (tylko dla nowych plików)"))
        self.e32_tooltip.setToolTip(_translate("Dialog", "Wartość identyfikująca rekord metadanych w unikalny sposób.\n"
"\n"
"Wartość elementu musi być równa identyfikatorowi UUID.\n"
""))
        self.mGroupBox_12_5.setTitle(_translate("Dialog", "Standard metadanych*"))
        self.e33_lbl.setText(_translate("Dialog", "Nazwa standardu metadanych*"))
        self.e33_lineEdit.setText(_translate("Dialog", "ISO 19115"))
        self.e33_tooltip.setToolTip(_translate("Dialog", "Nazwa standardu metadanych użytego do opisu zbioru danych przestrzennych."))
        self.e34_lbl.setText(_translate("Dialog", "Wersja standardu metadanych*"))
        self.e34_lineEdit.setText(_translate("Dialog", "2005/Amd 1:2008"))
        self.e34_tooltip.setToolTip(_translate("Dialog", "Wersja standardu metadanych użytego do opisu zbioru."))
        self.send_lbl.setText(_translate("Dialog", "Wybierz, gdzie chcesz wysłać plik z metadanymi (opcjonalne):"))
        self.server_btn.setText(_translate("Dialog", "Wyślij na serwer katalogowy"))
        self.email_btn.setText(_translate("Dialog", "Wyślij na adres email"))
        self.prev_btn.setText(_translate("Dialog", "Wstecz"))
        self.validateAndSave_btn.setText(_translate("Dialog", "Waliduj/zapisz"))
        self.close_btn.setText(_translate("Dialog", "Zakończ"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsdatetimeedit import QgsDateTimeEdit
from qgsfilewidget import QgsFileWidget
from qgsfilterlineedit import QgsFilterLineEdit
