# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules/metadata/views/ui/smtp_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_smtp_dlg(object):
    def setupUi(self, smtp_dlg):
        smtp_dlg.setObjectName("smtp_dlg")
        smtp_dlg.resize(411, 258)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(smtp_dlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalGroupBox = QtWidgets.QGroupBox(smtp_dlg)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.host_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.host_lbl.setObjectName("host_lbl")
        self.horizontalLayout.addWidget(self.host_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.host_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.host_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.host_lineEdit.setProperty("qgisRelation", "")
        self.host_lineEdit.setObjectName("host_lineEdit")
        self.horizontalLayout.addWidget(self.host_lineEdit)
        self.host_chkbx = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.host_chkbx.setObjectName("host_chkbx")
        self.horizontalLayout.addWidget(self.host_chkbx)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.port_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.port_lbl.setObjectName("port_lbl")
        self.horizontalLayout_4.addWidget(self.port_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.port_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.port_lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.port_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.port_lineEdit.setInputMask("")
        self.port_lineEdit.setText("")
        self.port_lineEdit.setMaxLength(6)
        self.port_lineEdit.setProperty("qgisRelation", "")
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.horizontalLayout_4.addWidget(self.port_lineEdit)
        self.port_chkbx = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.port_chkbx.setObjectName("port_chkbx")
        self.horizontalLayout_4.addWidget(self.port_chkbx)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.user_lbl.setObjectName("user_lbl")
        self.horizontalLayout_3.addWidget(self.user_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.user_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.user_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.user_lineEdit.setProperty("qgisRelation", "")
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.horizontalLayout_3.addWidget(self.user_lineEdit)
        self.user_chkbx = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.user_chkbx.setEnabled(False)
        self.user_chkbx.setObjectName("user_chkbx")
        self.horizontalLayout_3.addWidget(self.user_chkbx)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pass_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.pass_lbl.setObjectName("pass_lbl")
        self.horizontalLayout_5.addWidget(self.pass_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pass_lineEdit = QgsPasswordLineEdit(self.verticalGroupBox)
        self.pass_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.pass_lineEdit.setObjectName("pass_lineEdit")
        self.horizontalLayout_5.addWidget(self.pass_lineEdit)
        self.pass_chkbx = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.pass_chkbx.setEnabled(False)
        self.pass_chkbx.setObjectName("pass_chkbx")
        self.horizontalLayout_5.addWidget(self.pass_chkbx)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.receiver_lbl = QtWidgets.QLabel(self.verticalGroupBox)
        self.receiver_lbl.setObjectName("receiver_lbl")
        self.horizontalLayout_2.addWidget(self.receiver_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.receiver_lineEdit = QgsFilterLineEdit(self.verticalGroupBox)
        self.receiver_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.receiver_lineEdit.setProperty("qgisRelation", "")
        self.receiver_lineEdit.setObjectName("receiver_lineEdit")
        self.horizontalLayout_2.addWidget(self.receiver_lineEdit)
        self.receiver_chkbx = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.receiver_chkbx.setEnabled(False)
        self.receiver_chkbx.setObjectName("receiver_chkbx")
        self.horizontalLayout_2.addWidget(self.receiver_chkbx)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.verticalGroupBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.save_btn = QtWidgets.QPushButton(smtp_dlg)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_6.addWidget(self.save_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.send_btn = QtWidgets.QPushButton(smtp_dlg)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_6.addWidget(self.send_btn)
        self.cancel_btn = QtWidgets.QPushButton(smtp_dlg)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_6.addWidget(self.cancel_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(smtp_dlg)
        QtCore.QMetaObject.connectSlotsByName(smtp_dlg)

    def retranslateUi(self, smtp_dlg):
        _translate = QtCore.QCoreApplication.translate
        smtp_dlg.setWindowTitle(_translate("smtp_dlg", "Wysyłanie metadanych na email"))
        self.verticalGroupBox.setTitle(_translate("smtp_dlg", "parametry połaczenia SMTP"))
        self.host_lbl.setText(_translate("smtp_dlg", "host          "))
        self.host_lineEdit.setPlaceholderText(_translate("smtp_dlg", "np:. smtp.gmail.com"))
        self.host_chkbx.setText(_translate("smtp_dlg", "zapisz"))
        self.port_lbl.setText(_translate("smtp_dlg", "port          "))
        self.port_lineEdit.setPlaceholderText(_translate("smtp_dlg", "np.: 587"))
        self.port_chkbx.setText(_translate("smtp_dlg", "zapisz"))
        self.user_lbl.setText(_translate("smtp_dlg", "użytkownik"))
        self.user_lineEdit.setPlaceholderText(_translate("smtp_dlg", "np.: jan.kowalski@gmail.com"))
        self.user_chkbx.setText(_translate("smtp_dlg", "zapisz"))
        self.pass_lbl.setText(_translate("smtp_dlg", "hasło        "))
        self.pass_chkbx.setText(_translate("smtp_dlg", "zapisz"))
        self.receiver_lbl.setText(_translate("smtp_dlg", "adresat     "))
        self.receiver_lineEdit.setPlaceholderText(_translate("smtp_dlg", "np.: jan.kowalski@gmail.com"))
        self.receiver_chkbx.setText(_translate("smtp_dlg", "zapisz"))
        self.save_btn.setText(_translate("smtp_dlg", "Zapisz"))
        self.send_btn.setText(_translate("smtp_dlg", "Wyślij"))
        self.cancel_btn.setText(_translate("smtp_dlg", "Anuluj"))

from qgsfilterlineedit import QgsFilterLineEdit
from qgspasswordlineedit import QgsPasswordLineEdit
